### ISSUE TITLE
UseCorrelationTracking might fail with NotSupportedException

### ISSUE THREAD

**Issue by Alterling** [albumprinter/CorrelationTracking#38]
In the case of .NET Framework project + .NetStandard dependencies + System.Net.Http from nuget next code `new HttpClient().UseCorrelationTracking()` might throw NotSupportedException. As a workaround we had to use `new HttpClient(new CorrelationDelegatingHandler { InnerHandler = new LoggingDelegatingHandler(true) { InnerHandler = new HttpClientHandler() } })`

**Comment by derwasp** [comment]
Closing this as we are moving away from manual delegating handlers
